version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      # Сохраняем базу данных SQLite
      - ./sqlite:/app/.tmp
      - ./database.sqlite:/app/database.sqlite
      # Сохраняем загруженные файлы
      - ./public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://mintence.com/strapi
    container_name: frontend
    ports:
      - "3010:3010"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:1337
      - NODE_ENV=production

networks:
  app_network:
    driver: bridge
