version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_FILENAME=/opt/.tmp/data.db
    volumes:
      - ./backend/.tmp:/opt/.tmp
      - ./backend/public/uploads:/opt/public/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:1337
