version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:1337

  backend:
    build: ./backend
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=sqlite
      - NODE_ENV=production
    volumes:
      - ./backend/public:/app/public
      - ./backend/.tmp:/app/.tmp
