version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      # Сохраняем базу данных SQLite
      - ./sqlite:/app/.tmp
      - ./database.sqlite:/app/database.sqlite
      # Сохраняем загруженные файлы
      - ./public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3010:3010"
    depends_on:
      - backend
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  app_network:
    driver: bridge
