version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:1337

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend  # Монтируем папку backend в контейнер
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=sqlite
      - NODE_ENV=production
