version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production

  # если нужен фронт, то, например:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:1337
    depends_on:
      - backend
