# Базовый образ для Next.js
FROM node:18

WORKDIR /app

# Копируем весь frontend код
COPY ./frontend /app/frontend

WORKDIR /app/frontend

# Устанавливаем зависимости
RUN yarn install

# Строим Next.js проект
RUN yarn build

# Открываем порт 3005 для Next.js
EXPOSE 3005

# Запускаем Next.js сервер
CMD ["yarn", "start"]
